#!/bin/sh

program_dir=/usr/pbi/sabnzbdplus-$(uname -m)
tmpfile=$(mktemp /tmp/.XXXXXX)

grep -v 'sabnzbd_' /etc/rc.conf > ${tmpfile}
cat ${program_dir}/etc/rc.conf >> ${tmpfile}
mv ${tmpfile} /etc/rc.conf
